### ISSUE TITLE
Implement Bottom Navigation in Main Activity

### ISSUE THREAD

**Issue by Dradeon** [dkimjpg/SendScribbles#7]
# Tasks:
- [x] Create Bottom Navigation in Main Activity
- [x] Add Icons and Text
- [x] Configure Logic for the Bottom Navigation
